[package]
distribution = "2201.10.0"
org = "ballerina"
name = "etl"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["etl"]

repository = "https://github.com/ballerina-platform/module-ballerina-etl"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "etl-native"
version = "@toml.version@"
path = "../native/build/libs/etl-native-@project.version@.jar"