[package]
org = "induwarag"
name = "enrich_customer_data"
version = "0.1.0"
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "etl"
version = "1.0.0"
repository="local"